FROM php:5.6-apache-stretch

RUN a2enmod headers rewrite \
    && apt-get update && apt-get install --no-install-recommends -y \
      ghostscript \
      imagemagick \
      libfreetype6-dev \
      libicu-dev \
      libjpeg-dev \
      libmagickcore-dev \
      libmagickwand-dev \
      libpng-dev \
      libpq-dev \
      libxslt-dev \
      unzip \
    && pecl channel-update pecl.php.net \
    && pecl install redis-4.3.0 xdebug-2.5.5 imagick \
    && docker-php-ext-enable redis xdebug imagick \
    && docker-php-ext-configure intl --with-icu-dir=/usr \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include \
    && docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd \
    && docker-php-ext-configure mysqli --with-mysqli=mysqlnd \
    && docker-php-ext-install zip calendar bcmath bz2 exif opcache xsl intl gd pdo_mysql pdo_pgsql mysql mysqli \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /tmp/* \
    && php -r "copy('https://getcomposer.org/composer.phar', 'composer.phar');" \
    && mv composer.phar /usr/local/bin/composer \
    && chmod +x /usr/local/bin/composer \
    && mkdir /docker-entrypoint.d
    
COPY docker-php-entrypoint /usr/local/bin/
COPY docker-configure-session /docker-entrypoint.d
