#!/bin/sh
set -e

# Run all entrypoint script present in /docker-entrypoint.d directory
DIR=/docker-entrypoint.d

if [ -d "$DIR" ]
then
  /bin/run-parts "$DIR"
fi

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
  set -- php-fpm "$@"
fi

exec "$@"