#!/bin/sh

if [ "${PHP_SESSION_SAVE_HANDLER}" ]
then
  echo "PHP Session will be stored with $PHP_SESSION_SAVE_HANDLER handler"
  echo "session.save_handler = $PHP_SESSION_SAVE_HANDLER" > /usr/local/etc/php/conf.d/sessions.ini
  if [ "${PHP_SESSION_SAVE_PATH}" ]
  then
    echo "PHP Session will be stored in $PHP_SESSION_SAVE_PATH"
    echo "session.save_path = $PHP_SESSION_SAVE_PATH" >> /usr/local/etc/php/conf.d/sessions.ini
  fi
fi
