FROM php:5.5-apache

RUN printf "deb http://archive.debian.org/debian/ jessie main\ndeb-src http://archive.debian.org/debian/ jessie main\ndeb http://security.debian.org jessie/updates main\ndeb-src http://security.debian.org jessie/updates main" > /etc/apt/sources.list

# Install composer
COPY --from=composer /usr/bin/composer /usr/bin/composer

# Enable rewrite mod of apache
RUN a2enmod rewrite

# Update apt cache and install tools
RUN apt-get update && apt-get install --no-install-recommends -y unzip

# Install php-redis
RUN pecl install redis-4.3.0 && docker-php-ext-enable redis

# Install php-imagick
RUN apt-get install --no-install-recommends --force-yes -y libmagickcore-dev libmagickwand-dev imagemagick ghostscript \
    && pecl install imagick && docker-php-ext-enable imagick

# Install php-intl
RUN apt-get install --no-install-recommends -y libicu-dev \
    && docker-php-ext-configure intl --with-icu-dir=/usr && docker-php-ext-install intl

# Install php-gd
RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include && docker-php-ext-install gd

# Install php-pdo_mysql
RUN docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd && docker-php-ext-install pdo_mysql

# Install php-pdo_pgsql
RUN apt-get install --no-install-recommends -y libpq-dev && docker-php-ext-install pdo_pgsql

# Install php-mysql
RUN docker-php-ext-install mysql

# Install php-mysqli
RUN docker-php-ext-configure mysqli --with-mysqli=mysqlnd && docker-php-ext-install mysqli

# Install php-xsl
RUN apt-get install --no-install-recommends -y libxslt-dev && docker-php-ext-install xsl

# Install php-zip
RUN docker-php-ext-install zip

# Install php-calendar
RUN docker-php-ext-install calendar

# Install php-bcmath
RUN docker-php-ext-install bcmath

# Install php-bz2
RUN docker-php-ext-install bz2

# Install php-exif
RUN docker-php-ext-install exif

# Install php-opcache
RUN docker-php-ext-install opcache

# Install php-xdebug
RUN pecl install xdebug-2.5.5 && docker-php-ext-enable xdebug

# Clean apt cache
RUN rm -rf /var/lib/apt/lists/*

# Clean tmp
RUN rm -rf /tmp/*
